services:
  pihole:
    image: docker.io/pihole/pihole:2025.11.0 # https://hub.docker.com/r/pihole/pihole/tags
    pull_policy: always
    container_name: pihole
    restart: always
    hostname: pi400
    networks:
      - pihole
      - dnscrypt
    ports:
      - 53:53/tcp
      - 53:53/udp
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/pihole/volumes/pihole:/etc/pihole:Z
      - ${DATA_PATH}/pihole/configs/99-edns.conf:/etc/dnsmasq.d/99-edns.conf:Z
    cap_add:
      - CAP_SYS_TIME
      - CAP_SYS_NICE

networks:
  pihole:
    external: true
  dnscrypt:
    external: true