services:
  syncthing:
    image: docker.io/syncthing/syncthing:2.0.14 # https://hub.docker.com/r/syncthing/syncthing/tags
    pull_policy: always
    container_name: syncthing
    hostname: homelab
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - syncthing
    volumes:
      - ${DATA_PATH}/syncthing/volumes/syncthing:/var/syncthing:Z
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp

networks:
  syncthing:
    external: true