services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v2.5.5 # https://github.com/immich-app/immich/releases
    volumes:
      - ${DATA_PATH}/immich/volumes/immich:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - config.env
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - immich
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.5 # https://github.com/immich-app/immich/pkgs/container/immich-machine-learning
    volumes:
      - ${DATA_PATH}/immich/volumes/machine-learning:/cache
    env_file:
      - config.env
    restart: always
    networks:
      - immich
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:8.4.0-alpine # https://hub.docker.com/_/redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  immich-postgres:
    container_name: immich-postgres
    image: ghcr.io/immich-app/postgres:17-vectorchord0.5.3-pgvector0.8.1 # https://github.com/immich-app/base-images/pkgs/container/postgres
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/immich/volumes/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - immich

networks:
  immich:
    external: true