services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:14.0.2 # https://codeberg.org/forgejo/-/packages/container/forgejo/versions
    pull_policy: always
    container_name: forgejo
    restart: always
    networks:
      - forgejo
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/forgejo/volumes/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - forgejo-postgres

  forgejo-postgres:
    container_name: forgejo-postgres
    image: docker.io/postgres:17.7-bookworm # https://hub.docker.com/_/postgres
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/forgejo/volumes/postgres:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - forgejo

networks:
  forgejo:
    external: true