services:
  vaultwarden:
    image: docker.io/vaultwarden/server:1.35.2 # https://github.com/dani-garcia/vaultwarden/releases
    pull_policy: always
    container_name: vaultwarden
    restart: always
    networks:
      - vaultwarden
    env_file:
      - config.env
    volumes:
      - ${DATA_PATH}/vaultwarden/volumes/vaultwarden:/data:Z

networks:
  vaultwarden:
    external: true